export { default as IconStudy } from './IconStudy'
export { default as IconExplorer } from './IconExplorer'
export { default as IconCourse } from './IconCourse'
export { default as IconMember } from './IconMember'
export { default as IconOrder } from './IconOrder'
export { default as IconStar } from './IconStar'
export { default as IconEye } from './IconEye'
export { default as IconClock } from './IconClock'
