/** @format */

import type { Metadata } from 'next'
import './globals.css'
import { manrope } from '@/utils'
import SideBar from '@/components/layout/sidebar'

export const metadata: Metadata = {
  title: 'Academy App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} font-primary`}>
        <div className="wrapper grid h-screen grid-cols-[300px,minmax(0,1fr)]">
          <SideBar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
