/** @format */

import type { Metadata } from 'next'
import './globals.css'
import { manrope } from '@/utils'
import SideBar from '@/components/layout/sidebar'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: 'Academy App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${manrope.className} font-primary`}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
